name: aegis_vault
description: "Modern Cloud Storage with Zero-Knowledge Encryption"
version: 3.5.5
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.0
  file_picker: ^8.0.0
  desktop_drop: ^0.4.0
  window_manager: ^0.3.0
  pointycastle: ^3.9.0
  crypto: ^3.0.0
  uuid: ^4.0.0
  html: ^0.15.0
  path: ^1.9.0
  collection: ^1.18.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.0

flutter:
  uses-material-design: true